### ISSUE TITLE
Force usage of "Predefined Repositories"

### ISSUE THREAD

**Issue by RobertPaasche** [NetworkedAssets/git4c#2]
Is there a way to force the usage of "Predefined Repositories". The shouldn't  be able to enter there own repository data (especially the ssh-key) at the macro definition (mask).

**Comment by bartoszbednarekna** [comment]
We will add such a functionality in a nearest release 1.3 in next days. 
It will work like this: 
You would be able to set "Force using predefined repo" in Administration and user then will not be allow to add custom repository.

**Comment by RobertPaasche** [comment]
Perfect.

**Comment by bartoszbednarekna** [comment]
Hello Robert, 

Git4C in version 1.3 is available at Atlassian Marketplace. "Force using predefined repo" in Administration area is ready to use. 

Best, 
NetworkedAssets
