### ISSUE TITLE
500 error saving repository

### ISSUE THREAD

**Issue by donbobbo4** [NetworkedAssets/git4c#7]
When saving a new repository in confluence or even just single file getting a 500 error for this GET request:

/rest/doc/1.0/documentation 

Response:
com.atlassian.activeobjects.internal.ActiveObjectsInitException: bundle [com.networkedassets.git4c.confluence-plugin]

I am able to see the preview correctly for single file macro but not able to save.

**Comment by bartoszbednarekna** [comment]
Hello, 
Think you for a Feedback. 

Can you give us more detalis:
1. What database do you use for Confluence?
2. How big is the repository?
3. How many files in total are in repository? 
4. Do you have enough free disk space in temp directory of Confluence to clone that repository?

**Comment by donbobbo4** [comment]
Answers inline.

> On Jan 8, 2018, at 1:01 PM, bartoszbednarekna <notifications@github.com> wrote:
> 
> Hello,
> Think you for a Feedback.
> 
> Can you give us more detalis:
> 
> What database do you use for Confluence?
AWS RDS - Postgres 9.5.4
> How big is the repository?
33.19 kb
> How many files in total are in repository?
70
> Do you have enough free disk space in temp directory of Confluence to clone that repository?

> /dev/xvda2                   10G  1.5G  8.5G  15% /
> devtmpfs                    3.8G     0  3.8G   0% /dev
> none                        3.7G     0  3.7G   0% /dev/shm
> tmpfs                       3.7G  217M  3.5G   6% /run
> tmpfs                       3.7G     0  3.7G   0% /sys/fs/cgroup
> /dev/mapper/sysvg-varvol    100G   65G   36G  65% /var
> /dev/mapper/sysvg-tmpvol    2.0G   33M  2.0G   2% /tmp
> /dev/mapper/sysvg-optvol    182G  4.6G  178G   3% /opt
> /dev/mapper/sysvg-logvol    2.0G  101M  1.9G   5% /var/log
> /dev/mapper/sysvg-auditvol  2.0G   86M  2.0G   5% /var/log/audit
> /dev/mapper/sysvg-homevol   2.0G   34M  2.0G   2% /home
> tmpfs                       757M     0  757M   0% /run/user/62385
> tmpfs                       757M     0  757M   0% /run/user/0—
> 

It looks like we do /tmp has 1.75.  The working directory confluence are

CATALINA_HOME: /opt/atlassian/confluence
CATALINA_TMPDIR: /opt/atlassian/confluence/temp 

I’m not sure if your using /tmp or confluence tmp.

**Comment by bartoszbednarekna** [comment]
At Atlassian Marketplace there is version 1.4 available. I suggest to update to the latest version. 
In this version we have added multiple logs on log level "info" that will help out to debug any possible problems. There is also added option to automatic repair cache problems and disk cache problems, so that most macro problems like: blocked cache, repository locks should be automaticly resolved. 

Please try the newest version and in case of problems let's try to gather "info" logs from the plugin.
